---
- name: Staging server Deployment
  hosts: stageserver
  become: True
  vars:
    repo_path: nrbaskar/hariapp:{{DOCKER_TAG}}
  tasks:
    # Install python pip
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    # Install docker service 
    - name: Install docker
      yum:
        name: docker
        state: present
    # Start the docker service
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    # Install docker-python Module
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    #Pull Docker Image    
    - name: Pull httpd docker image
      docker_image:
        name: hariapp
        tag: {{ repo_path }}
        source: pull
    #Copy Files
    - name: Copy website to the host
      copy:
        src: ./*
        dest: /home/ec2-user
    # Install NodeJS library
    # using multiple shell commands
    - name: Ansible shell module multiple commands
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'
    - name: Install reqired packages
      yum: name={{ item }} state=present
      with_items:
        - nodejs
    # Install all the necessary Node modules for the project,
    # using `npm`.
    - name: Install project dependencies
      command: npm install
      args:
        chdir: "{{ repo_path }}"
    # Install Forever tool.
    # This tool is used to run the Node server in background
    # and keep tracking of the running process
    - name: Install Forever
      npm: name=forever global=yes state=present
    # is already running (avoids restarting the service on each playbook
    # execution)
    - name: Get Forever's list of running processes
      command: forever list
      register: forever_list
      changed_when: false
    # Start the node server using "Foverer"
    # The `when` clause identifies if the server is already
    # running. If so, this task is skipped
    - name: Start service
      command: forever start app.js
      when: "forever_list.stdout.find('sample-node-project/app.js') == -1"
      args:
        chdir: "{{ repo_path }}"
